version: '2'

services:
  timelock:
    image: palantirtechnologies/timelock-server-distribution
    ports:
      - "8421"
      - "8422"

  cassandra:
    image: palantirtechnologies/docker-cassandra-atlasdb:$CASSANDRA_VERSION
    ports:
      - "9160"
      - "9042"
      - "7199"
    environment:
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - LOCAL_JMX=no

  ete1:
    build: .
    # We don't use console, because we might want to start/stop/restart the service.
    command: [bash, -c, '
        dockerize -timeout 120s -wait tcp://cassandra:9160
        && service/bin/init.sh start
        && tail -F var/log/startup.log']
    ports:
      - "3828"
    depends_on:
      - cassandra
      - timelock
    volumes:
      - $CONFIG_FILE_MOUNTPOINT:/atlasdb-ete/atlasdb-ete-snapshot/var/conf/
    environment:
      - ME=ete1
