version: '2'

services:
  timelock:
    image: palantirtechnologies/timelock-server-distribution
    ports:
      - "8421"
      - "8422"

  cassandra:
    image: palantirtechnologies/cassandra:$CASSANDRA_VERSION
    ports:
      - "9160"
      - "9042"
      - "7199"
    environment:
      - MAX_HEAP_SIZE=512m
      - HEAP_NEWSIZE=64m
      - LOCAL_JMX=no

  ete1:
    build: .
    command: [bash, -c, 'cp var/conf/atlasdb-ete.timelock.cassandra.yml var/conf/atlasdb-ete.yml && dockerize -timeout 120s -wait tcp://cassandra:9160 && service/bin/init.sh console']
    ports:
      - "3828"
    depends_on:
      - cassandra
      - timelock
    environment:
      - ME=ete1

  ete-cli:
    build: .
    entrypoint: [bash, -c, 'cp var/conf/atlasdb-ete.timelock.cassandra.yml var/conf/atlasdb-ete.yml && "$$@"', --]
    command: exit
    depends_on:
      - ete1
    environment:
      - ME=ete1
