version: '2'

services:
  cassandra:
    image: palantirtechnologies/docker-cassandra-atlasdb:2.2.9 # todo replace with $CASSANDRA_VERSION
    container_name: atlas_perf_cassandra
    ports:
      - "9160:9160"
      - "9042:9042"
      - "7199:7199"
    environment:
      - LOCAL_JMX=no
