version: '2'

services:
  postgres:
    image: kiasaki/alpine-postgres
    container_name: atlas_perf_postgres
    environment:
       POSTGRES_PASSWORD: palantir
       POSTGRES_USER: palantir
       POSTGRES_DB: atlas
    ports:
      - "5432:5432"